In [1]:
import pandas as pd
df = pd.read_csv('https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv')
df.head()

,activity_id,institution_id,source_id,experiment_id,member_id,table_id,variable_id,grid_label,zstore,dcpp_init_year,version
0,HighResMIP,CMCC,CMCC-CM2-HR4,highresSST-present,r1i1p1f1,Amon,ps,gn,gs://cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/...,NaN,20170706
1,HighResMIP,CMCC,CMCC-CM2-HR4,highresSST-present,r1i1p1f1,Amon,rsds,gn,gs://cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/...,NaN,20170706
2,HighResMIP,CMCC,CMCC-CM2-HR4,highresSST-present,r1i1p1f1,Amon,rlus,gn,gs://cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/...,NaN,20170706
3,HighResMIP,CMCC,CMCC-CM2-HR4,highresSST-present,r1i1p1f1,Amon,rlds,gn,gs://cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/...,NaN,20170706
4,HighResMIP,CMCC,CMCC-CM2-HR4,highresSST-present,r1i1p1f1,Amon,psl,gn,gs://cmip6/CMIP6/HighResMIP/CMCC/CMCC-CM2-HR4/...,NaN,20170706

In [13]:
models_ = ["MIROC6", "MRI-ESM2-0", "NorESM2-MM", "GFDL-ESM4", "ACCESS-ESM1-5", "IPSL-CM6A-LR"]
[i for i in models_ if i not in df['source_id'].unique()]

[]

In [7]:
df_ta = df.query("activity_id=='CMIP' & table_id == 'day' & variable_id == 'prc' & experiment_id != 'historical'")
df_ta

,activity_id,institution_id,source_id,experiment_id,member_id,table_id,variable_id,grid_label,zstore,dcpp_init_year,version
797,CMIP,CNRM-CERFACS,CNRM-CM6-1,1pctCO2,r1i1p1f2,day,prc,gr,gs://cmip6/CMIP6/CMIP/CNRM-CERFACS/CNRM-CM6-1/...,NaN,20180626
1960,CMIP,NOAA-GFDL,GFDL-CM4,piControl,r1i1p1f1,day,prc,gr2,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-CM4/piCon...,NaN,20180701
3048,CMIP,NOAA-GFDL,GFDL-CM4,piControl,r1i1p1f1,day,prc,gr1,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-CM4/piCon...,NaN,20180701
10220,CMIP,NOAA-GFDL,GFDL-CM4,amip,r1i1p1f1,day,prc,gr2,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-CM4/amip/...,NaN,20180701
10240,CMIP,NOAA-GFDL,GFDL-CM4,amip,r1i1p1f1,day,prc,gr1,gs://cmip6/CMIP6/CMIP/NOAA-GFDL/GFDL-CM4/amip/...,NaN,20180701
...,...,...,...,...,...,...,...,...,...,...,...
513084,CMIP,NCC,NorESM2-LM,abrupt-4xCO2,r1i1p1f1,day,prc,gn,gs://cmip6/CMIP6/CMIP/NCC/NorESM2-LM/abrupt-4x...,NaN,20210118
514664,CMIP,AS-RCEC,TaiESM1,abrupt-4xCO2,r1i1p1f1,day,prc,gn,gs://cmip6/CMIP6/CMIP/AS-RCEC/TaiESM1/abrupt-4...,NaN,20210215
514813,CMIP,IPSL,IPSL-CM5A2-INCA,piControl,r1i1p1f1,day,prc,gr,gs://cmip6/CMIP6/CMIP/IPSL/IPSL-CM5A2-INCA/piC...,NaN,20210216
515217,CMIP,CMCC,CMCC-ESM2,piControl,r1i1p1f1,day,prc,gn,gs://cmip6/CMIP6/CMIP/CMCC/CMCC-ESM2/piControl...,NaN,20210304
515285,CMIP,CMCC,CMCC-CM2-HR4,1pctCO2,r1i1p1f1,day,prc,gn,gs://cmip6/CMIP6/CMIP/CMCC/CMCC-CM2-HR4/1pctCO...,NaN,20210304

In [14]:
df_ta['experiment_id'].unique()

array(['1pctCO2', 'piControl', 'amip', 'abrupt-4xCO2'], dtype=object)